"""Added permissions

Revision ID: e52759549cd6
Revises: cea50be03703
Create Date: 2023-07-16 22:58:18.532552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52759549cd6'
down_revision = 'cea50be03703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
